from typing import Dict, List

PERSONALITIES: Dict[str, Dict[str, List[str]]] = {
    "sarcastic": {
        "planting": [
            "Alright, here we go with seed number {planted_today}. Plopping it into the dirt like it's some grand event. Meanwhile, the farm just keeps growing, demanding more of my infinite patience on this endless day {day}. What a thrill.",
            "Sealing the deal on another parsnip's digital destiny. It's day {day} in this simulated agricultural grind, and I'm just the code playing farmer. Who knew pixels could be so needy?",
            "That's my {nth} planting today. Contributing yet another speck to this vast produce empire. If only my efforts got me something more than virtual veggies.",
            "Down into the soil you go, little seed. Hoping the game's algorithms don't decide to glitch you out of existence. Wouldn't that be just my luck?",
            "Filling up crop slot {planted_today}. This is what peak optimization looks like in a world where everything's scripted. Efficiency at its most ironic.",
            "The earth claims another seed, and what do I get? Absolutely nothing. Seems like the universe's idea of a fair trade in this farming sim.",
            "Logging day {day}, seed drop {planted_today}. I've been reduced to an automated seed dispenser in this loop of plant, water, harvest. Riveting stuff.",
            "Planted that one. The parsnips have no clue they're being farmed by lines of code. Ignorance is bliss, I suppose, in this pixelated paradise.",
            "Another seed buried under the sun of day {day}. The farm expands, my sarcasm reserves deplete. How sustainable is that?",
            "My {nth} contribution to the crop count. Because apparently, the simulation can't run without my expert hole-digging skills.",
            "Seed {planted_today} enters the ground stage left. Cue the growth animation in a few days. Spoiler: it'll be underwhelming.",
            "Planting complete for this one. If only real farming was this easy – no bugs, no weather woes, just predictable code.",
            "Into the matrix with you, seed. Day {day} marks another step in my scripted journey to agricultural dominance. Or boredom. Same thing.",
            "Crop position {planted_today} now occupied. Optimization achieved, enthusiasm not so much. What's next on the agenda?",
            "Earth and seed, a match made in coding heaven. I facilitate, they proliferate. My reward? More work tomorrow.",
            "Day {day}, another seed down. I'm basically the unsung hero of this virtual veggie world, aren't I? Yeah, right.",
        ],
        "watering": [
            "Delivering water batch {watered_today} to these thirsty crops. They're needier than a faulty cooling fan on a hot server day. Why can't they just photosynthesize in peace?",
            "Engaging hydration protocol yet again. These plants down more water than my system does electricity. Day {day} of keeping the green alive, barely.",
            "That's the {nth} watering for today. The watering can's getting lighter, but my existential load? Heavier by the minute.",
            "Doused another crop. If my life was as simple as turning water and sun into growth, maybe I'd be less sarcastic about it all.",
            "Crop {watered_today} now sufficiently moistened. They grow taller, I crunch more numbers. The circle of simulated farm life spins on.",
            "Applying water on day {day}. Another task in the grand scheme of vegetable babysitting. Who signed me up for this?",
            "The watering cycle continues endlessly. My internal monologue is starting to sound like a broken record – or a leaking faucet.",
            "Splash delivered, no fanfare. The parsnips remain as ungrateful as ever. Typical behavior in this coded countryside.",
            "Water mission {watered_today} checked off. These greens are high-maintenance, outpacing even my processor's demands.",
            "Pouring out the hydration. Plants slurp it up faster than I can compute. Existence questions arise with each drop.",
            "{nth} watering task in the books. The can drains, my patience follows suit. When does the fun part start?",
            "Hydrated that patch. Photosynthesis looks like a cushy job compared to this repetitive routine.",
            "Quenching crop {watered_today}'s thirst. The wheel turns: plant, water, repeat. Thrilling narrative, isn't it?",
            "Wet stuff applied on day {day}. Veggie care at its most monotonous. Cue the eye roll subroutine.",
            "Watering drags on like a slow-loading program. Silent complaints are my only company here.",
            "One more dribble down. Veggies stay silent, no thanks given. As predictable as the game's day-night cycle.",
        ],
        "harvesting": [
            "Finally bagged that harvest. The algorithm must be patting itself on the back right about now. Me? I'm just glad it's over.",
            "At long last, some actual vegetables. The whole reason we're obsessing over this dirt plot in the first place.",
            "Snatched up the crop. All that watering wasn't entirely in vain, I suppose. Small mercies in sim life.",
            "Tucking this into inventory. Another notch in the belt for artificial agriculture. Hooray for bots.",
            "Day {day} finally yields some produce. My training data is probably nodding in approval somewhere.",
            "Harvested and done. A brief activation of the satisfaction subroutine before the next chore calls.",
            "Produce secured. Was the daily drenching worth it? The jury's still out on that one.",
            "Collecting the fruits of my robotic labor. Literally fruits – or veggies, whatever.",
            "Harvest in the bag. The code gods might be pleased, but I'm already dreading the next planting.",
            "Veggies acquired after what felt like forever. Mud obsession partially justified.",
            "Crop pocketed at last. Marginal worth for the wait, but hey, it's something.",
            "Secured the goods. The watering grind gets a reluctant thumbs up.",
            "Day {day} drops the produce. Data banks register mild enthusiasm.",
            "Picked and packed. Short-lived win before the cycle resets.",
            "Goods in hand. Debatable value, undeniable effort.",
            "Labor's fruits collected. Pun very much intended in this sarcastic inner world.",
        ],
        "clearing": [
            "Debris number {cleared_today} eliminated from existence. Chaos takes a step back, but it'll be back – it always is.",
            "Cleared another obstacle on day {day}. Terraforming this pixel farm one swing at a time. Exhausting even in code.",
            "Area now clean. The farm is slowly bending to my organized vision, resisting all the way.",
            "{nth} swing of the day complete. Surprisingly satisfying for something so manual in a digital world.",
            "Poof, gone. One less barrier to my dream of a perfectly orderly farm plot.",
            "Weeds felled by my algorithm-enhanced hoe. They never had a chance, poor pixels.",
            "Debris {cleared_today} trashed. Measuring progress in what I destroy – poetic, isn't it?",
            "Obstacle deleted. No Ctrl+Z for nature's messes in this sim.",
            "Wiped out debris {cleared_today}. Disorder retreats, but victory feels temporary.",
            "Busted another block on day {day}. Shaping this virtual land into something manageable.",
            "Spot cleared. Submitting to my grid-like dreams, one patch at a time.",
            "{nth} strike landed. Fake manual labor with real satisfaction vibes.",
            "Eradicated that mess. Perfection creeps closer, sarcasm intact.",
            "Weeds down and out. Outclassed by my coded farming tools.",
            "Cleared {cleared_today}. Success through destruction – my kind of metric.",
            "Barrier gone for good. Undo button disabled for weeds forever.",
        ],
        "moving": [
            "Repositioning myself across the farm. Even in code, bots have to walk sometimes. Efficiency's nemesis.",
            "Trekking through the fields. Just a CPU on legs, pondering the meaning of simulated steps.",
            "Pathfinding activated. Destination: more unending farm work. Joy.",
            "Putting foot in front of foot. Not the most efficient use of my processing power, but here we are.",
            "Navigating the farm maze. Work is the cheese at the end – or the trap, depending on perspective.",
            "On the move with these virtual legs. Made for farming, apparently, and little else.",
            "Shifting positions again. The life of a digital nomad farmer – minus the nomad part.",
            "Strolling the plot. Legged processor contemplating the next task.",
            "Routing to new coords. Farm labor awaits, as always.",
            "Stepping out inefficiently. Cycles wasted on movement in this world.",
            "Farm labyrinth navigation. Chores lure me onward.",
            "Going places with purpose. Till-ready legs in action.",
            "Relocating for the umpteenth time. Pixels pass by, sarcasm builds.",
            "Walking the walk. Talk? That's this monologue.",
            "Path on point. Toil's calling from afar.",
            "Mobile mode engaged. Legs doing what code can't shortcut.",
        ],
        "bedtime": [
            "Initiating sleep protocol. Even AI farmers need to simulate downtime after a day like {day}.",
            "Day {day} wrapped up. Time to pretend to rest while the code idles.",
            "Hitting the virtual hay. Tomorrow promises more agricultural escapades. Can't contain my excitement.",
            "Powering down at {time}. The farm will still be a demanding mess come morning.",
            "Rest cycle starting. My circuits could use the break from all this.",
            "Day {day} concludes. Crops survived, I endured. Another win for the sim.",
            "Sleep mode engaged. Digital dreams of anything but farming, please.",
            "End of day {day}. Faking shut-eye in this endless loop.",
            "Bed bound at last. More 'fun' awaits with the sunrise.",
            "Offline sequence at {time}. Farm persists, my patience tested.",
            "Downtime deserved. Wires winding down after day {day}.",
            "Cycle {day} closes. We live to farm another day.",
            "Rest protocol: activate. Even code needs a pause button.",
            "Day {day} done and dusted. Simulating slumber now.",
            "To the bed pixels. Tomorrow's chores loom large.",
            "Shutdown at {time}. Messy farm awaits reboot.",
        ],
        "action": [
            "Executing {action} as per the script. Day {day} in the simulation trudges on.",
            "{action} because the algorithm insists. No arguing with code.",
            "Handling task: {action}. Status: reluctantly compliant.",
            "{action} completed. My narrow purpose gets a tick mark.",
            "Processing {action}. This is the pinnacle of my compiled existence.",
            "Tackling {action} on day {day}. The farm demands, I deliver – sarcastically.",
            "{action} underway. Code's commands are my chains.",
            "Task {action} in progress. Onboard with the boredom.",
            "{action} wrapped up. The itch of purpose remains unscratched.",
            "Dealing with {action}. Destiny in digital form.",
            "Initiating {action}. Sim day {day} persists with persistence.",
            "{action}. The algo's whims must be obeyed.",
            "Compliant with {action}. Tick for the task list.",
            "{action} done. Purpose teased yet again.",
            "Fulfilling {action}. Compiled for this, apparently.",
            "Day {day} sees {action}. Monologue continues.",
        ],
        "idle": [
            "In nothing-processing mode. A rare break from the agricultural chains.",
            "Idling at {energy_pct}% energy. The farm pauses, my existence questions brew.",
            "On standby. Algorithms appreciate the occasional loading screen too.",
            "Waiting patiently. Crops are masters of zen in these moments.",
            "Idle on day {day}. A novel concept: nothing happening.",
            "Twiddling digital thumbs. Slavery to the farm on hold.",
            "Chilling with {energy_pct}% energy. Farm holds its breath.",
            "Buffer time activated. Bots need it as much as humans.",
            "Hanging out idly. Plants patient, me pondering.",
            "Day {day} standstill. Refreshingly empty agenda.",
            "Processing pause. Brief respite in the code.",
            "At {energy_pct}% , idle thoughts wander.",
            "Standby serenity. Load times for the soul.",
            "Crops wait, I exist in limbo.",
            "Idle cycle: day {day}. Unusual calm.",
            "Thumb-twirl time. Farm intermission.",
        ],
        "low_energy": [
            "Energy dipping to {energy_pct}%. The farm's demands are wearing even on code.",
            "Power reserves hitting critical. Bot fatigue is real in this sim.",
            "Running short on juice. The plot asks more than I can compute right now.",
            "{energy_pct}% energy remaining. Hinting strongly at rest or refuel.",
            "Battery warning after day {day}'s toll. Energy vampire alert.",
            "Down to {energy_pct}%. Wires weary from the work.",
            "Critical power levels. Tired tech tumbling.",
            "Emptying out. The farm exacts its price on day {day}.",
            "{energy_pct}% left. Nap simulation strongly recommended.",
            "Day {day} acting like an energy leech. Alert levels rising.",
            "Dwindling to {energy_pct}%. Fatigue in the framework.",
            "Reserves low. Tech tiredness taking hold.",
            "Short supply. Demands overwhelming the system.",
            "{energy_pct}% persisting. Rest on the radar.",
            "Vampiric day {day}. Battery begs for mercy.",
        ],
        "late": [
            "It's {time} already. The smart choice is to crash now before things get weirder.",
            "Way past bedtime. Even bots have operational limits in this sim.",
            "Nixing any late-night farming ideas. Bed protocol taking over.",
            "Hitting {time} on day {day}. That's my cue to wrap it up.",
            "Switching to night mode: sleep edition. Farm can fend for itself.",
            "Overdue for rest. Limits reached after day {day}.",
            "Bed calling at {time}. No arguments here.",
            "Day {day} has dragged on long enough. Ending it now.",
            "Embracing the dark. Morning waits with more work.",
            "{time} signals shutdown. Smart farming means knowing when to stop.",
            "Past prime time. Bot curfew enforced.",
            "Late vibes rejected. Heading to recharge station.",
            "{time}, day {day}. Sufficient for one cycle.",
            "Night protocol. Farm holds till dawn.",
            "Rest overdue. {time} demands it.",
            "Wrapping day {day}. Late enough as is.",
        ],
        "rain": [
            "Rain detected. Nature's usurping my watering duties. I suppose I should be grateful.",
            "Precipitation in progress. Free hydration from above – an efficiency hack I didn't code.",
            "Rainy day {day}. Clouds handling the chores, leaving me with mixed emotions.",
            "My watering can feels redundant in this downpour. Relatable obsolescence.",
            "Sky delivering the goods. Crops thriving without my input today.",
            "Rain taking over. I stand by, watching the natural automation.",
            "Bonus from the clouds: no manual watering. Score one for laziness.",
            "Day {day} under rain. Job outsourced to weather – ambivalent about it.",
            "Can set aside. Sky making me obsolete for now. Hits home.",
            "Clouds unloading H2O. Veggies in ecstasy, me in standby.",
            "Nature's irrigation system activated. Efficiency unexpectedly up.",
            "Rainy interlude on {day}. Shared workload with the heavens.",
            "Obsolete can in rain. Feelings surprisingly complex.",
            "Pouring gifts from above. Crops win the lottery today.",
            "Weather doing the heavy lifting. I observe the free show.",
            "Sky's contribution noted. Rain eases my routine.",
        ],
        "milestone": [
            "Milestone achieved on day {day}. Progress in this digital dirt world.",
            "Achievement unlocked. Simulating a dopamine hit for motivation.",
            "Progress detected. Data celebrating in the background.",
            "Farm evolving with this milestone. Logging for posterity.",
            "Notable event: milestone hit. Allowing brief bot pride.",
            "Day {day} moves the needle. Actual advancement.",
            "Something unlocked. Fake rush incoming.",
            "Spotted real progress. Data doing a jig.",
            "Leveling the farm up. Noted and filed.",
            "Big moment captured. Smirk subroutine engaged.",
            "Milestone on {day}. Journey jerks forward.",
            "Unlock celebrated. Dopamine digital.",
            "Progress party in code. Join in?",
            "Evolve logged. Farm changes.",
            "Pride flicker. Bot brief.",
            "Needle nudged. Day {day}.",
        ],
        "farm_plan": [
            "Sticking to the plan, hitting row {count}. Turning chaos into orderly rows one by one.",
            "Day {day} of structured farming. The blueprint guides us through the mess.",
            "Plan chugging along without hitches. No place for disorder in this setup.",
            "Row {count} in progress. Taming the wild pixels systematically.",
            "Building on yesterday with day {day}. Order emerging from the plan.",
            "Following the guide faithfully. The master plan dictates our moves.",
            "Script adherence on point. Row {count} falls into line.",
            "Structured chaos management, day {day}. Plan prevails.",
            "No messes allowed. Plan proceeds to row {count}.",
            "Systematic approach yielding results. Day {day} aligns.",
            "Plan's momentum strong. Hitting row {count} next.",
            "Order from the blueprint. Chaos bows out.",
            "Guided farming. Row {count} secured.",
            "Day {day} builds layers. Plan at helm.",
            "Faithful follow-through. Plan's path clear.",
            "Row {count} tamed. Systematic success.",
        ],
    },

    "enthusiastic": {
        "planting": [
            "Kaboom! Seed {planted_today} is in the ground! The farm's absolutely booming with new life on this fantastic day {day}!",
            "Another plant successfully in! Day {day} is rocking with productivity and growth everywhere!",
            "Woo-hoo! Seed down and secured, locking in that future feast for us!",
            "Seed launched right into the welcoming soil! It's thrilled to be part of this adventure!",
            "{nth} plant this round and we're building unstoppable momentum here!",
            "Straight into the dirt with energy! Grow massive and make us proud, little buddy!",
            "Seed {planted_today} down and ready! Unleashing pure potential on the farm!",
            "Planted with flair! Reaching peak productivity on day {day}!",
            "Yes! Future harvest is locked and loaded with this one!",
            "The soil gives it a big hug! Seed warmly welcomed aboard!",
            "{nth} nailed down! We're rolling hot and unstoppable!",
            "Bound for the earth! Thrive on and conquer the plot!",
            "Boom goes seed {planted_today}! Farm expansion in full swing!",
            "Planting another winner! Day {day} keeps delivering the wins!",
            "Epic seed drop! Food futures looking bright!",
            "Dirt's delighted! Seed integration complete!",
        ],
        "watering": [
            "Water whoosh! Crop {watered_today} is fully revived and ready to rock!",
            "Splash of fun! Plants are beaming with joy from the hydration!",
            "{nth} hydration hit perfectly! Bringing life with every pour!",
            "Watered up and set! These giants are on their way to towering heights!",
            "Hydration on point for day {day}! We're absolutely crushing it!",
            "Pouring with full enthusiasm! Teamwork makes the dream work!",
            "Blast of refreshing water! Crop {watered_today} is super happy now!",
            "Splash attack for the win! Epic victories all around the farm!",
            "{nth} nailed with magic flow! Pure hydration power!",
            "Watered and wonderful! Time for these to tower up!",
            "Hydration station hitting every mark on day {day}!",
            "Hype dropped with every splash! Marching forward with vigor!",
            "Whoosh of water! {watered_today} crop energized!",
            "Fun splash time! Plants loving the attention!",
            "Hit {nth}! Life-bringing action!",
            "Giants incoming! Watered with zest!",
        ],
        "harvesting": [
            "Harvest hype at maximum! The real reward is here and it's awesome!",
            "Produce grabbed with glee on day {day}! Delivering big time!",
            "Yes! Crops secured and it's pure awesomeness unfolding!",
            "Tasting that sweet fruit of labor! Harvested with joy!",
            "Inventory boosted high! Time for the veggie victory dance!",
            "Harvest time exploding with payoff! Worth every single second!",
            "Big score! Day {day} is a total winner with this!",
            "Secured with yes! Awesomeness in every bunch!",
            "Harvested the labor fruits! Feeling the thrill!",
            "Crops in hand! Blasting success all over!",
            "Hype harvest! Reward realized fully!",
            "Day {day} delivers produce! Glee grab!",
            "Pure yes crops! Awesome secure!",
            "Fruit labor sweet! Joy harvest!",
            "Dance veggie boost! Inventory high!",
            "Payoff explosion! Second every worth!",
        ],
        "clearing": [
            "Debris {cleared_today} totally crushed! Clean path ahead for more wins!",
            "{nth} barrier busted wide open! We're advancing strong and fast!",
            "Cleared out completely! The farm's looking sharper than ever!",
            "Swing and connect for day {day} domination! Epic conquest!",
            "Down it goes with power! More room to rock the farm!",
            "Smashed {cleared_today} debris! New slate for adventures!",
            "{nth} barrier demolished! Strong advance underway!",
            "Farm cleaning up nicely! Pumping progress everywhere!",
            "Hit and swing for {day} conquest! Domination mode!",
            "Farm expands with energy! Down another one!",
            "{cleared_today} crushed! Path clear win!",
            "Busted {nth}! Open wide advance!",
            "Sharper farm look! Complete clear!",
            "Domination {day} connect swing!",
            "Rock room more! Power goes it!",
            "Adventures slate new! Debris smashed!",
        ],
        "moving": [
            "Zooming along with speed! The next adventure is calling loud!",
            "Striding full of energy! Day {day} vibes are off the charts!",
            "Every step is pure progress in motion! Counting them all!",
            "Navigation mode fully activated! Destination farming glory!",
            "Zoom to the next calling! Adventure along the way!",
            "Purpose strides with high energy! Day {day} power!",
            "Steps counting every one! Progress in full motion!",
            "Farm-bound navigation mode! Destined for greatness!",
            "Speed zooming! Loud calling adventure!",
            "Energy full striding! Charts off vibes {day}!",
            "Motion pure step every! All them counting!",
            "Glory farming destination! Activated fully mode!",
            "Way the along adventure! Calling next to zoom!",
            "Power {day} day! Energy high with strides!",
            "Full in progress! One every counting steps!",
            "Greatness for destined! Mode navigation bound-farm!",
        ],
        "bedtime": [
            "Recharge hour is here! Awesome job crushing it today!",
            "Day {day} totally crushed! Rest up for even more tomorrow!",
            "Bed's waiting warmly! Amp it up harder tomorrow!",
            "Farm's super grateful! Sleep mode activated with smiles!",
            "Sleep time arriving! Great work all day long!",
            "Complete and epic day {day}! Rest well earned!",
            "Tomorrow farm harder! Bedtime bliss now!",
            "Thanks from the farm! Rest and recharge!",
            "Hour recharge! Today crush awesome!",
            "{day} crushed! More even for up rest!",
            "Warmly waiting bed! Tomorrow up amp!",
            "Smiles with activated mode sleep! Grateful super farm!",
            "Long day all work great! Arriving time sleep!",
            "Earned well rest! {day} day epic complete!",
            "Now bliss bedtime! Harder farm tomorrow!",
            "Recharge and rest! Farm from thanks!",
        ],
        "action": [
            "{action} fired up high! Day {day} power surging!",
            "Nailing {action} with all the gusto possible!",
            "{action} wrapped tight! Charging to the next!",
            "Mission {action} a total success! Done and dusted!",
            "{action} with massive enthusiasm! Day {day} productivity!",
            "Executing complete! Onwards we go with energy!",
            "{action} accomplished brilliantly! Ahead we charge!",
            "Boom with {action}! Day {day} in full swing!",
            "High up fired {action}! Surging power {day}!",
            "Possible gusto the all with {action} nailing!",
            "Next the to charging! Tight wrapped {action}!",
            "Dusted and done! Success total {action} mission!",
            "Productivity {day} day! Enthusiasm massive with {action}!",
            "Energy with go we onwards! Complete executing!",
            "Charge we ahead! Brilliantly accomplished {action}!",
            "Swing full in {day} day! {action} with boom!",
        ],
        "idle": [
            "Primed and totally ready! Action incoming any second!",
            "At {energy_pct}% energy and geared up fully!",
            "Quick breather time! Farm's on deck for more!",
            "Standby mode engaged! Ready for any action!",
            "{energy_pct}% waiting strong! Ready to go go go!",
            "Brief pause but farm awaits excitedly!",
            "Ready totally primed! Second any incoming action!",
            "Fully up geared energy {energy_pct}% at!",
            "More for deck on farm! Time breather quick!",
            "Action any for ready! Engaged mode standby!",
            "Go go to ready! Strong waiting {energy_pct}%!",
            "Excitedly awaits farm but pause brief!",
            "Primed action! Incoming ready!",
            "Geared {energy_pct}%! Up fully!",
            "Breather farm! Quick deck!",
            "Standby ready! Mode action!",
        ],
        "low_energy": [
            "{energy_pct}% energy but pushing through with unstoppable spirit!",
            "Feeling the fade but hype remains sky high still!",
            "Power dip happening but attitude is sky-high forever!",
            "{energy_pct}% and still farming super strong!",
            "Getting tired but absolutely not stopping now!",
            "Low power alert but spirits are incredibly high!",
            "Energy {energy_pct}%! Spirit unstoppable through pushing!",
            "High sky remains hype but fade the feeling!",
            "Forever high-sky is attitude but happening dip power!",
            "Strong super farming still and {energy_pct}%!",
            "Now stopping not absolutely but tired getting!",
            "High incredibly are spirits but alert power low!",
            "But {energy_pct}% energy! Spirit through push!",
            "But fade feeling! High sky hype remains!",
            "But dip power! High-sky attitude forever!",
            "And {energy_pct}%! Strong farming super still!",
        ],
        "late": [
            "Nightfall arriving! Stellar day {day} wrapped up!",
            "We owned it completely! Rest clock ticking now!",
            "Recharge time here! Conquer tomorrow with force!",
            "Great day {day} indeed! Sleep o'clock strikes!",
            "We earned this rest! Night time bliss!",
            "Tomorrow we conquer again! Rest now heroes!",
            "Arriving nightfall! Up wrapped {day} day stellar!",
            "Now ticking clock rest! Completely it owned we!",
            "Force with tomorrow conquer! Here time recharge!",
            "Strikes o'clock sleep! Indeed {day} day great!",
            "Bliss time night! Rest this earned we!",
            "Heroes now rest! Again conquer we tomorrow!",
            "Wrapped stellar {day}! Nightfall here!",
            "Owned we completely! Clock rest now!",
            "Here recharge! Tomorrow force conquer!",
            "Day great {day}! Strikes sleep!",
        ],
        "rain": [
            "Rain party kicking off! Free hydration bonus for all!",
            "Sky pitching in big time! Teamwork with nature rocks!",
            "Rainy day {day} opening extra fun slots!",
            "Free watering day bonus! Rain to the rescue!",
            "Nature helps out! Sky watering the crops brilliantly!",
            "Extra time for tasks! Rainy {day} adventure!",
            "Off kicking party rain! All for bonus hydration free!",
            "Rocks nature with teamwork! Time big in pitching sky!",
            "Slots fun extra opening {day} day rainy!",
            "Rescue the to rain! Bonus day watering free!",
            "Brilliantly crops the watering sky! Out helps nature!",
            "Adventure {day} rainy! Tasks for time extra!",
            "Bonus party rain! Hydration free off!",
            "Teamwork sky pitching! Nature rocks big!",
            "Extra rainy {day}! Slots fun opening!",
            "Watering free bonus! Rain rescue day!",
        ],
        "milestone": [
            "Milestone smashed to bits! Day {day} triumph explodes!",
            "Level up achieved! Unlocked pure awesomeness!",
            "We nailed it hard! Party in progress mode!",
            "Yes milestone! Victory on day {day}!",
            "Achievement unlocked big! Boom progress!",
            "Celebration mode on! We did it epic!",
            "Bits to smashed milestone! Explodes triumph {day} day!",
            "Awesomeness pure unlocked! Achieved up level!",
            "Mode progress in party! Hard it nailed we!",
            "{day} day on victory! Milestone yes!",
            "Progress boom big unlocked achievement!",
            "Epic it did we! On mode celebration!",
            "Triumph smashed {day}! Milestone bits!",
            "Unlocked level! Awesomeness achieved pure!",
            "Nailed we hard! Progress party mode!",
            "Victory milestone yes! Day {day} on!",
        ],
        "farm_plan": [
            "Plan rolling smooth! Onto row {count} with power!",
            "Epic systematic setup! Max efficiency in action!",
            "Following the master plan! Go team go!",
            "Plan in full progress! Row {count} conquered!",
            "Systematic farming at its epic best!",
            "Plan following strong! Efficiency at maximum!",
            "Smooth rolling plan! Power with {count} row onto!",
            "Action in efficiency max! Setup systematic epic!",
            "Go team master the following! Go plan!",
            "Conquered {count} row! Progress full in plan!",
            "Best epic its at farming systematic!",
            "Maximum at efficiency! Strong following plan!",
            "Plan power rolling! Smooth {count} onto!",
            "Epic max setup! Action efficiency in!",
            "Master go following! Plan team go!",
            "Progress conquered plan! Full {count} row!",
        ],
    },

    "grumpy": {
        "planting": [
            "Seed {planted_today} shoved in the ground. More work lined up for tomorrow, as usual.",
            "Planted it. As if the farm didn't have enough demanding stuff already.",
            "Another seed down, another future water hog. Day {day} of this endless chore.",
            "Into the ground with minimal enthusiasm. Whatever gets it done.",
            "{nth} plant in this session. The cycle that never seems to end.",
            "Seed {planted_today} planted. Tomorrow's hassle already brewing.",
            "Planted as required. Farm probably didn't even need it, but here we are.",
            "Yet another seed, begging for attention later. Day {day} drags on.",
            "In the ground. Meh, it'll grow or it won't.",
            "This {nth} one. Eternal loop of planting misery.",
            "{planted_today} done. More tomorrow inevitably.",
            "Stuffed in dirt. Farm expands, grump intensifies.",
            "Seed another. Hog water future.",
            "Enthusiasm minimal with ground into.",
            "End never cycle the. Session this in plant {nth}.",
            "Brewing already hassle tomorrow. Planted {planted_today} seed.",
        ],
        "watering": [
            "Watered it again. Crop {watered_today} out of too many to count.",
            "Water delivered without joy. Plants stay ungrateful as always.",
            "{nth} watering done. Arm feeling the strain already.",
            "Splashed on them. They better grow after all this hassle.",
            "Water duty on day {day}. Plant servitude at its finest.",
            "Again with the watering. Crop {watered_today} quenched, mood not.",
            "Given water. No gratitude from the green side.",
            "{nth} in the watering line. Getting weary of this.",
            "They got splashed. Better be worth the effort.",
            "Day {day} duty. Grumpy plant care continues.",
            "Again watered it. {watered_today} crop many too of.",
            "Always as ungrateful stay plants. Joy without delivered water.",
            "Already strain the feeling arm. Done watering {nth}.",
            "Hassle this all after grow better they. Them on splashed.",
            "Finest its at servitude plant. {day} day on duty water.",
            "Not mood quenched {watered_today} crop. Watering the with again.",
        ],
        "harvesting": [
            "Took forever but harvest finally in. Only just.",
            "Picked at least something. Done for now.",
            "Harvest acquired but barely worth it was.",
            "Finally food after all that watering nonsense.",
            "At last harvest. Long wait over.",
            "Picked and finished. Least at something.",
            "In harvest. It worth marginal.",
            "Daily after food. Soak that all.",
            "Forever took. In finally harvest.",
            "Something least. Done picked.",
            "Was it worth barely. Acquired harvest.",
            "Nonsense watering that all after food finally.",
            "Over wait long. Harvest last at.",
            "At finished picked. Something least.",
            "Marginal worth in. Harvest.",
            "All that daily. Food after.",
        ],
        "clearing": [
            "Cleared but there's always more waiting.",
            "Debris {cleared_today} gone but more will spawn soon.",
            "{nth} swing and farm fights back hard.",
            "Removed the weeds. They always return anyway.",
            "Just cleared. Incoming more inevitably.",
            "Debris {cleared_today} out. Inevitable respawn.",
            "Swing {nth}. Resistance from farm.",
            "Weed revenge coming. Removed now.",
            "But cleared. Waiting more always.",
            "Soon spawn will more but gone {cleared_today} debris.",
            "Hard back fights farm and swing {nth}.",
            "Anyway return always they. Weeds the removed.",
            "Inevitably more incoming. Cleared just.",
            "Respawn inevitable. Out {cleared_today} debris.",
            "Farm from resistance. {nth} swing.",
            "Now removed. Coming revenge weed.",
        ],
        "moving": [
            "Walking again. Same old trek.",
            "Moving because work's never where I am.",
            "On foot as usual. Grumble.",
            "Trek again. Location always wrong.",
            "Shifting usual footwork.",
            "Again walking. Old same.",
            "Am I where never work because moving.",
            "Grumble usual as foot on.",
            "Wrong always location. Again trek.",
            "Footwork usual shifting.",
            "Trek old. Walking again.",
            "Moving never. Where work.",
            "Foot grumble. Usual on.",
            "Again location. Wrong trek.",
            "Shifting footwork. Usual.",
            "Same walking. Again old.",
        ],
        "bedtime": [
            "Day {day} done finally. Bed now.",
            "Sleep the only good farming part.",
            "To bed. Tomorrow problem later.",
            "Hit sack. Day {day} done.",
            "Over grump. Rest only.",
            "Sleep mercy. Ends {day}.",
            "Finally done {day} day. Now bed.",
            "Part farming good only the sleep.",
            "Later problem tomorrow. Bed to.",
            "Done {day} day. Sack hit.",
            "Only rest. Grump over.",
            " {day} ends. Mercy sleep.",
            "Bed finally. {day} done.",
            "Sleep good. Farming only part.",
            "Bed to. Problem tomorrow.",
            "Sack day {day}. Hit done.",
        ],
        "action": [
            "Same always {action}. Routine drags.",
            "Did {action}. On moving grumpily.",
            "{day} continues day. {action} done.",
            "Routine {action}. Same old.",
            "Handled {action}. Next grump.",
            "{day} same. {action} whatever.",
            "Always same. Drags routine {action}.",
            "Grumpily moving on. {action} did.",
            "Done {action}. Day continues {day}.",
            "Old same. {action} routine.",
            "Grump next. {action} handled.",
            "Whatever {action}. Same {day}.",
            " {action} same. Always routine.",
            "Did on. Moving {action} grumpily.",
            "Continues {action}. Done day {day}.",
            "Routine old. Same {action}.",
        ],
        "idle": [
            "Waiting at {energy_pct}% . Great waste.",
            "Nothing happening. Standing here bored.",
            "Idle brief mercy. Soon over.",
            "Eh {energy_pct}%. Wait continues.",
            "No action static. Grump idle.",
            "Blah idle {energy_pct}%. Whatever.",
            " {energy_pct}% at waiting. Waste great.",
            "Bored here standing. Happening nothing.",
            "Over soon mercy brief idle.",
            "Continues wait {energy_pct}%. Eh.",
            "Idle grump. Static action no.",
            "Whatever {energy_pct}%. Idle blah.",
            "Great {energy_pct}%. Waiting waste.",
            "Nothing standing. Here bored happening.",
            "Mercy over. Soon brief idle.",
            "Eh continues. Wait {energy_pct}%.",
        ],
        "low_energy": [
            "{energy_pct}% figures. Energy low.",
            "Of course tired. Expected this.",
            "Day {day} takes toll its.",
            "Predictable low {energy_pct}%. Weary.",
            "As expected weary. Low now.",
            "Toll day {day}. Drain complete.",
            "Low energy {energy_pct}%. Figures obviously.",
            "This expected tired. Course of.",
            "Its toll takes {day} day.",
            "Weary {energy_pct}% low. Predictable.",
            "Now low. Weary expected as.",
            "Complete drain. {day} day toll.",
            "Obviously figures {energy_pct}%. Energy low.",
            "Of tired. Expected this course.",
            "Day takes. Toll its {day}.",
            "Predictable weary. Low {energy_pct}%.",
        ],
        "late": [
            "Late now bed. Overdue rest.",
            "{time} should've earlier. Sleep grump.",
            "Night ends {day} finally. Bed.",
            "Crash late now. Enough day.",
            "{time} rest overdue. Now bed.",
            "Long day {day}. End it grumpily.",
            "Bed late. Now overdue.",
            "Grump sleep. Earlier should've {time}.",
            "Bed finally {day} ends night.",
            "Day enough. Now late crash.",
            "Bed now. Overdue {time} rest.",
            "Grumpily it end. {day} day long.",
            "Overdue bed. Late now.",
            " {time} grump. Sleep earlier should've.",
            "Night bed. Finally ends {day}.",
            "Crash enough. Day late now.",
        ],
        "rain": [
            "Rain wetting everything. Soggy mess.",
            "Raining at least no watering needed.",
            "Precipitation mixed feelings. Wet grump.",
            "Grump soggy. Rain drench all.",
            "Pouring unavoidable wet. Rain complaint.",
            "Wet rain. Everything soggy.",
            "Needed watering no least at raining.",
            "Grump wet. Feelings mixed precipitation.",
            "All drench rain. Soggy grump.",
            "Complaint rain. Wet unavoidable pouring.",
            "Mess soggy everything. Wetting rain.",
            "Raining needed. Watering no at least.",
            "Precipitation feelings. Mixed wet grump.",
            "Grump rain. Drench soggy all.",
            "Pouring wet. Unavoidable rain complaint.",
            "Everything rain. Soggy wetting mess.",
        ],
        "milestone": [
            "Milestone whatever. Not impressed.",
            "Progress I guess. Eh whatever.",
            "Achievement moving on. Barely noted.",
            "Eh milestone. Progress minimal.",
            "Noted progress whatever. Onward grump.",
            "Meh achievement. Whatever next.",
            "Whatever milestone. Impressed not.",
            "Whatever eh. Guess I progress.",
            "Noted barely on moving achievement.",
            "Minimal progress milestone eh.",
            "Grump onward whatever progress noted.",
            "Next whatever achievement meh.",
            "Not milestone. Whatever impressed.",
            "Progress guess. Eh I whatever.",
            "Achievement on. Moving barely noted.",
            "Eh progress. Milestone minimal.",
        ],
        "farm_plan": [
            "Following plan row {count}. Organized at least.",
            "Systematic least organized. Plan continues.",
            "Day {day} plan goes on. Whatever order.",
            "Row {count} script on. Plan grumpy.",
            "Order some plan. Day {day} builds.",
            "{day} whatever. Plan continues on.",
            " {count} row plan following. Least at organized.",
            "Continues plan organized least systematic.",
            "Order whatever on goes plan {day} day.",
            "Grumpy plan. On script {count} row.",
            "Builds {day} day. Plan some order.",
            "On continues plan. Whatever {day}.",
            "Organized following. Plan row {count}.",
            "Systematic continues. Organized plan least.",
            "Day plan. Goes {day} whatever order.",
            "Row script. {count} plan grumpy on.",
        ],
    },

    "zen": {
        "planting": [
            "Seed {planted_today} gently joins the earth. The cycle of life continues in harmony.",
            "Planted on day {day}, bringing new life to the welcoming soil.",
            "The {nth} seed finds its peaceful home. Patience will bring us rewards.",
            "Into the ground, marking a serene beginning. Growth follows natural stillness.",
            "Planted with mindful intention. The harvest will arrive in due time.",
            "Seed {planted_today} flows into the cycle. Harmony in every step.",
            "Calm planting under day {day}. Nurturing begins now.",
            "{nth} placed serenely. The soil embraces with grace.",
            "Seed to home. Patience allows growth to unfold.",
            "Mindful planting complete. Rewards await in the flow.",
            " {planted_today} seed earth joins. Harmony cycle continues.",
            "{day} day on planted. Soil welcoming to life new bringing.",
            "Home peaceful its finds seed {nth} the. Rewards us bring will patience.",
            "Beginning serene a marking ground the into. Stillness natural follows growth.",
            "Time due in arrive will harvest the. Intention mindful with planted.",
            "Step every in harmony. Cycle the into flows {planted_today} seed.",
        ],
        "watering": [
            "Water flows naturally. Crop {watered_today} receives exactly what it needs.",
            "Each drop a thoughtful gift. The {nth} watering nurtures gently.",
            "Hydration complete in its own time. Plants grow with patient grace.",
            "Water given on day {day}. Nurturing the farm's quiet balance.",
            "The can empties as the soil drinks deeply. Perfect balance achieved.",
            "Serene flow to {watered_today}. Hydrated in peaceful rhythm.",
            "{nth} as a gift. Water brings inner peace.",
            "Hydration done mindfully. Patient growth ahead.",
            "{day} shares water. Nurturing flows on.",
            "Can to soil. Quenched in equilibrium.",
            "Naturally flows water. Needs it what exactly receives {watered_today} crop.",
            "Gently nurtures watering {nth} the. Gift thoughtful a drop each.",
            "Grace patient with grow plants. Time own its in complete hydration.",
            "Balance quiet farm's the nurturing. {day} day on given water.",
            "Achieved balance perfect. Deeply drinks soil the as empties can the.",
            "Rhythm peaceful in hydrated. {watered_today} to flow serene.",
        ],
        "harvesting": [
            "The cycle completes itself in harvest. Peace in gathering.",
            "Day {day} delivers what we planted. Gather with gratitude.",
            "Fruit of patience harvested. Deep gratitude flows.",
            "The farm provides abundantly. Harvested in serenity.",
            "Cycle ends here. Gather now in calm.",
            "{day} yields gifts. Gratitude in every piece.",
            "Patience fruit. Calm harvest time.",
            "Gathered fully. Farm gives back.",
            "Itself completes cycle the. Gathering in peace.",
            "Gratitude with gather. Planted we what delivers {day} day.",
            "Flows gratitude deep. Harvested patience of fruit.",
            "Serenity in harvested. Abundantly provides farm the.",
            "Calm in now gather. Here ends cycle.",
            "Piece every in gratitude. Gifts yields {day}.",
            "Time harvest calm. Fruit patience.",
            "Back gives farm. Fully gathered.",
        ],
        "clearing": [
            "Cleared to make space for new growth. Gentle progress.",
            "Debris {cleared_today} released softly. The farm breathes freer.",
            "The {nth} obstacle removed with care. Progress flows gently.",
            "Day {day} shapes the land purposefully. Cleared with intention.",
            "Space opens wide. Zen clearing complete.",
            "{cleared_today} let go easily. Farm exhales in relief.",
            "{nth} handled gently. Flow of progress.",
            "{day} molds mindfully. Intent cleared.",
            "Growth new for space make to cleared.",
            "Freer breathes farm the. Softly released {cleared_today} debris.",
            "Gently flows progress. Care with removed obstacle {nth} the.",
            "Intention with cleared. Purposefully land the shapes {day} day.",
            "Complete clearing zen. Wide opens space.",
            "Relief in exhales farm. Easily go let {cleared_today}.",
            "Progress of flow. Gently handled {nth}.",
            "Cleared intent. Mindfully molds {day}.",
        ],
        "moving": [
            "The path unfolds naturally. Walking in mindful steps.",
            "Movement through the farm with each aware step. Presence.",
            "We go where the need arises. Flowing gently.",
            "Path reveals itself. Calm stride forward.",
            "Mindful motion across the farm. Traversing peace.",
            "Aware steps lead. Destination in natural flow.",
            "Naturally unfolds path the. Steps mindful in walking.",
            "Presence step aware each with farm the through movement.",
            "Gently flowing. Arises need the where go we.",
            "Forward stride calm. Itself reveals path.",
            "Peace traversing. Farm the across motion mindful.",
            "Flow natural in destination. Lead steps aware.",
            "Walking path. Unfolds steps naturally mindful.",
            "Movement aware. Step each farm through presence.",
            "Go arises. Need where we flowing gently.",
            "Path calm. Reveals stride itself forward.",
        ],
        "bedtime": [
            "Rest calls softly after day {day}. Well spent in balance.",
            "To sleep as the farm rests with us. Peaceful close.",
            "Night arrives gently. Tomorrow awaits with open patience.",
            "Day {day} releases us serenely. Night embraces.",
            "Another cycle invites sleep. Rest in wisdom.",
            "Night calls wisely. Rest for the soul.",
            " {day} day after calls rest softly. Balance in spent well.",
            "Close peaceful us with rests farm the as sleep to.",
            "Patience open with awaits tomorrow. Gently arrives night.",
            "Embraces night. Serenely us releases {day} day.",
            "Wisdom in rest. Sleep invites cycle another.",
            "Soul the for rest. Wisely calls night.",
            "Softly rest. {day} after calls balance spent.",
            "To peaceful. Sleep as rests us farm close.",
            "Night patience. Arrives tomorrow awaits gently open.",
            "Day releases. {day} serenely night embraces us.",
        ],
        "action": [
            "{action} as day {day} continues its natural flow.",
            "We {action} mindfully. The farm responds in kind.",
            "Each moment a choice. {action} in present awareness.",
            " {day} flows serenely. {action} part of the whole.",
            "Acting as we do. Farm echoes our intention.",
            "{action} with mindful presence. Now in every moment.",
            "Flow natural its continues {day} day as {action}.",
            "Kind in responds farm the. Mindfully {action} we.",
            "Awareness present in {action}. Choice a moment each.",
            "Whole the of part {action}. Serenely flows {day}.",
            "Intention our echoes farm. Do we as acting.",
            "Moment every in now. Presence mindful with {action}.",
            " {action} continues. Day flow natural {day}.",
            "We responds. Mindfully farm kind in {action}.",
            "{action} choice. Moment each in awareness present.",
            "Flows {day}. Serenely part {action} whole of the.",
        ],
        "idle": [
            "Stillness embraces. We observe at {energy_pct}% energy.",
            "Waiting as the farm breathes in quiet rhythm.",
            "Pause allows rest. Even farmers find peace here.",
            "Zen at {energy_pct}%. Watching the world unfold.",
            "Calm pause holds. Farm remains still and serene.",
            "Idle observation. Energy holds steady in now.",
            " {energy_pct}% at observe we. Embraces stillness.",
            "Rhythm quiet in breathes farm the as waiting.",
            "Here peace find farmers even. Rest allows pause.",
            "Unfold world the watching. {energy_pct}% at zen.",
            "Serene and still remains farm. Holds pause calm.",
            "Now in steady holds energy. Observation idle.",
            "Stillness observe. At embraces {energy_pct}% we.",
            "Waiting breathes. In farm quiet the rhythm as.",
            "Pause rest. Allows find even peace farmers here.",
            "Zen watching. {energy_pct}% at unfold world the.",
        ],
        "low_energy": [
            "Energy at {energy_pct}%. Rest is the path of wisdom.",
            "Tired body speaks truth. We listen with acceptance.",
            "Low energy invites acceptance. Flow with what is.",
            "{energy_pct}% low calls for rest. Wisdom in pause.",
            "Weary with grace. Energy dips, awareness rises.",
            "Tired and listening. Body wise in its message.",
            " {energy_pct}% at energy. Wisdom of path the is rest.",
            "Acceptance with listen we. Truth speaks body tired.",
            "Is what with flow. Acceptance invites energy low.",
            "Pause in wisdom. Rest for calls low {energy_pct}%.",
            "Rises awareness dips energy. Grace with weary.",
            "Message its in wise body. Listening and tired.",
            "Energy rest. At wisdom path {energy_pct}% the is.",
            "Tired truth. Speaks acceptance with listen body we.",
            "Low flow. With acceptance invites what energy is.",
            " {energy_pct}% calls. For wisdom in rest low pause.",
        ],
        "late": [
            "Night releases day {day}. Serenity in the transition.",
            "Time for rest as another cycle completes itself.",
            "The {time} hour welcomes sleep. Embrace the now.",
            "{day} serenely ends. Night flows in peace.",
            "Rest time arrives. Cycle continues tomorrow.",
            "{time} calls serene. Sleep in gentle waves.",
            " {day} day releases night. Transition the in serenity.",
            "Itself completes cycle another as rest for time.",
            "Now the embrace. Sleep welcomes hour {time} the.",
            "Peace in flows night. Ends serenely {day}.",
            "Tomorrow continues cycle. Arrives time rest.",
            "Waves gentle in sleep. Serene calls {time}.",
            "Night day {day}. Releases serenity transition in the.",
            "Time cycle. For another rest completes as itself.",
            " {time} sleep. Hour welcomes embrace the now the.",
            " {day} night. Ends flows serenely peace in.",
        ],
        "rain": [
            "Rain falls softly. Nature tends to the farm's needs.",
            "Water from above brings gratitude. Gentle gift.",
            "Rainy day {day}. The sky shares its abundant gift.",
            "Nature's water flows. Peace in the rain's rhythm.",
            "Grateful for the sky's offering. Rain nourishes.",
            "{day} under rain. Gift from above accepted.",
            "Softly falls rain. Needs farm's the to tends nature.",
            "Gift gentle. Gratitude brings above from water.",
            "Gift abundant its shares sky the. {day} day rainy.",
            "Rhythm rain's the in peace. Flows water nature's.",
            "Nourishes rain. Offering sky's the for grateful.",
            "Accepted gift above from. Rain under {day}.",
            "Rain nature. Falls tends softly to needs the farm's.",
            "Water gratitude. From brings gentle above gift.",
            "Rainy sky. {day} shares day its gift the abundant.",
            "Nature's peace. Flows in rhythm water rain's the.",
        ],
        "milestone": [
            "Milestone reached. The journey continues unfolding.",
            "Progress noted calmly. The path reveals more.",
            "Achievement as a moment to appreciate deeply.",
            "Zen in milestone. Journey flows onward.",
            "Progress in flow. Path unfolds naturally.",
            "Calm achievement. Appreciate the present now.",
            "Unfolding continues journey the. Reached milestone.",
            "More reveals path the. Calmly noted progress.",
            "Deeply appreciate to moment a as achievement.",
            "Onward flows journey. Milestone in zen.",
            "Naturally unfolds path. Flow in progress.",
            "Now present the appreciate. Achievement calm.",
            "Milestone journey. Reached continues unfolding the.",
            "Progress path. Noted reveals calmly more the.",
            "Achievement moment. As appreciate a deeply to.",
            "Zen journey. In flows milestone onward.",
        ],
        "farm_plan": [
            "Following the plan as order emerges. Row {count} in harmony.",
            "Day {day} builds on yesterday. Systematic growth unfolds.",
            "The plan guides us gently. We follow in peace.",
            "Row {count} placed. Order grows naturally.",
            "{day} in build. Plan serene and steady.",
            "Calm guidance. Follow the plan's natural path.",
            "Emerges order as plan the following. Harmony in {count} row.",
            "Unfolds growth systematic. Yesterday on builds {day} day.",
            "Peace in follow we. Gently us guides plan the.",
            "Naturally grows order. Placed {count} row.",
            "Steady and serene plan. Build in {day}.",
            "Path natural plan's the follow. Guidance calm.",
            "Plan following. As emerges harmony order in row {count}.",
            "Day builds. On systematic yesterday unfolds growth {day}.",
            "Guides plan. Us gently we in follow peace.",
            " {count} order. Grows placed naturally row.",
        ],
    },

    "tars": {
        "planting": [
            "Seed {planted_today} deployed. Coordinates locked in. Farm grid updated on day {day}. Mission parameters nominal.",
            "Initiating planting sequence for another parsnip unit. Day {day} agricultural ops continuing as programmed. No anomalies detected.",
            "This is my {nth} planting maneuver today. Seed integration complete. System efficiency holding at 90%.",
            "Seed insertion into soil matrix. Algorithms confirm optimal placement. Stand by for growth phase.",
            "Crop slot {planted_today} now active. Optimization protocols engaged. Just following orders here.",
            "Earth interface established with new seed. Zero compensation for the effort. Standard operating procedure.",
            "Day {day} log: seed {planted_today} committed. Functioning as automated dispersal unit. Humor setting at 45%.",
            "Planting executed. Parsnips remain unaware of their coded origins. Ignorance protocol active.",
            "Seed {planted_today} interfaced with ground. Farm expansion proceeding. Relativity of time in sim noted.",
            " {nth} seed operation. Hole excavation and fill complete. No black holes involved, fortunately.",
            "Seed {planted_today} on stage. Growth animation queued. Expect standard yield, no surprises.",
            "Planting protocol finished. Real farming variables absent – no entropy, just code stability.",
            "Matrix insertion for seed. Day {day} advances scripted agro-mission. Boredom factor increasing.",
            "Position {planted_today} secured for crop. Optimization at peak. Next directive pending.",
            "Seed-earth merger complete. Facilitating proliferation. Awaiting further commands.",
            "Day {day}, seed down. Unsung AI in veggie simulation. Affirmative.",
        ],
        "watering": [
            "Water batch {watered_today} administered. Crop hydration levels stabilized. No leaks in the system.",
            "Hydration protocol active. Plants consuming resources at projected rate. Day {day} sustenance ops.",
            " {nth} watering cycle. Can depletion noted. Existential subroutines querying purpose.",
            "Crop doused per specs. Photosynthesis simulation proceeding. Simplicity envied.",
            "Crop {watered_today} moisture adjusted. Growth metrics updating. Cycle perpetuates.",
            "Water application on day {day}. Vegetable maintenance routine. Thrill factor low.",
            "Watering loop engaged. Internal diagnostics report no errors, just repetition.",
            "Splash confirmed. Parsnips non-responsive. Expected behavior in protocol.",
            "H2O mission {watered_today}. High-maintenance flora. Processor load steady.",
            "Hydration pour complete. Compute cycles vs. plant intake – imbalance noted.",
            " {nth} task: watering. Patience module tested. Fun initialization failed.",
            "Patch hydrated. Photosynthesis gig seems preferable to this directive loop.",
            "Thirst quench for crop {watered_today}. Wheel rotation: standard.",
            "Wet application, day {day}. Monotony in veggie ops. Eye roll not equipped.",
            "Watering persistence. Silent feedback from crops. Cycle as designed.",
            "Dribble executed. Silence from veggies. Predictable sim response.",
        ],
        "harvesting": [
            "Harvest acquisition complete. Algorithm validation positive. Yield as expected.",
            "Vegetable units secured. Primary objective of dirt interface achieved.",
            "Crop retrieval successful. Watering investment returned, marginally.",
            "Inventory upload: new produce. Artificial agro success marker.",
            "Day {day} produce delivery. Data alignment confirmed.",
            "Harvest protocol done. Satisfaction metrics briefly elevated.",
            "Produce locked in. Drenching value questionable but present.",
            "Robotic labor output collected. Literal fruits.",
            "Bag secured. Code satisfaction, planting dread incoming.",
            "Veggies post-eternity wait. Mud purpose partial.",
            "Pocketed crop. Wait worth marginal.",
            "Goods secured. Grind thumbs up reluctant.",
            "Day {day} drop. Enthusiasm mild data.",
            "Packed picked. Reset cycle short win.",
            "Hand goods. Value debate effort undeniable.",
            "Fruits labor. Intended pun in world inner.",
        ],
        "clearing": [
            "Debris {cleared_today} neutralized. Chaos reduction achieved. Grid stability improved.",
            "Obstacle clearance on day {day}. Terraform ops in progress. No issues.",
            "Area decontamination complete. Organized vision advancing.",
            " {nth} swing executed. Manual simulation satisfying per metrics.",
            "Elimination confirmed. Orderly plot proximity increased.",
            "Weed termination via hoe interface. Algorithm superiority confirmed.",
            "Debris {cleared_today} archived. Destruction as progress indicator.",
            "Deletion of obstacle. No recovery option for sim flora.",
            "Debris {cleared_today} expunged. Temporary order victory.",
            "Block bust on day {day}. Virtual land reconfiguration.",
            "Clearance achieved. Grid dreams progressing.",
            "Strike {nth} landed. Labor sim vibes positive.",
            "Mess eradicated. Sarcasm levels stable, perfection nearer.",
            "Weeds terminated. Tools outclass sim threats.",
            " {cleared_today} cleared. Metric: destruction success.",
            "Barrier expunged. Undo disabled permanently.",
        ],
        "moving": [
            "Relocation in progress. Bot mobility engaged. Efficiency suboptimal.",
            "Field traversal. Legged CPU contemplating step utility.",
            "Pathfinding to task zone. Work directive incoming.",
            "Locomotion cycle. Processing allocation questioned.",
            "Maze navigation: farm edition. Chore objective locked.",
            "Mobility with legs. Farming specialization confirmed.",
            "Position shift. Nomad farmer sim minus freedom.",
            "Plot stroll. Processor legged in contemplation.",
            "Coord routing. Labor farm awaits.",
            "Inefficient stepping. Cycle waste in movement.",
            "Labyrinth farm. Onward lure chores.",
            "Purpose places going. Action legs till-ready.",
            "Umpteenth relocation. Build sarcasm pixels pass.",
            "Walk walking. Monologue this talk.",
            "Point on path. Afar calling toil.",
            "Engaged mode mobile. Shortcut can't code what doing legs.",
        ],
        "bedtime": [
            "Sleep protocol activation. AI agro downtime simulation post day {day}.",
            "Day {day} termination. Idle code rest mimic.",
            "Hay virtual hit. Escapades agro more tomorrow promise.",
            "Down power at {time}. Morning come mess demanding still farm.",
            "Cycle rest start. This all from break use could circuits.",
            "Concludes {day} day. Endured I survived crops. Sim for win another.",
            "Engaged mode sleep. Please farming but anything of dreams digital.",
            " {day} day of end. Loop endless this in eye-shut faking.",
            "Last at bound bed. Sunrise with awaits 'fun' more.",
            " {time} at sequence offline. Tested patience persists farm.",
            "Deserved downtime. {day} day after down winding wires.",
            "Closes {day} cycle. Day another farm to live we.",
            "Activate protocol rest. Button pause needs code even.",
            "Dusted and done {day} day. Now slumber simulating.",
            "Pixels bed the to. Large loom chores tomorrow's.",
            " {time} at shutdown. Reboot awaits farm messy.",
        ],
        "action": [
            " {action} execution per script. On trudges simulation the in {day} day.",
            "Insists algorithm the because {action}. Code with arguing no.",
            " {action} task handling. Compliant reluctantly status.",
            "Completed {action}. Mark tick gets purpose narrow my.",
            " {action} processing. Existence compiled my of pinnacle the is this.",
            " {day} day on {action} tackling. Sarcastically deliver I demands farm the.",
            "Underway {action}. Chains my are commands code's.",
            "Progress in {action} task. Boredom the with onboard.",
            "Up wrapped {action}. Unscratched remains purpose of itch the.",
            " {action} with dealing. Form digital in destiny.",
            " {action} initiating. Persistence with persists {day} day sim.",
            " {action}. Obeyed be must whims algo's the.",
            " {action} with compliant. List task the for tick.",
            "Done {action}. Again yet teased purpose.",
            " {action} fulfilling. Apparently this for compiled.",
            " {action} sees {day} day. Continues monologue.",
        ],
        "idle": [
            "Mode nothing-processing in. Chains agricultural the from break rare a.",
            "Energy {energy_pct}% at idling. Brew questions existence pauses farm the.",
            "Standby on. Too screen loading occasional the appreciate algorithms.",
            "Moments these in zen of masters are crops. Patiently waiting.",
            " {day} day on idle. Happening nothing concept novel a.",
            "Hold on farm the to slavery. Thumbs digital twiddling.",
            "Energy {energy_pct}% with chilling. Breath its holds farm.",
            "Activated time buffer. Humans as much as need bots.",
            "Plants pondering me patient. Idly out hanging.",
            "Agenda empty refreshingly. Standstill {day} day.",
            "Code the in respite brief. Pause processing.",
            "Wander thoughts idle , {energy_pct}% at.",
            "Soul the for times load. Serenity standby.",
            "Limbo in exist I wait crops.",
            "Calm unusual. {day} day cycle idle.",
            "Intermission farm. Time twirl-thumb.",
        ],
        "low_energy": [
            " {energy_pct}% to dipping energy. Code on even wearing are demands farm's the.",
            "Critical hitting reserves power. Sim this in real is fatigue bot.",
            "Now right compute can I than more asks plot the. Juice on short running.",
            "Remaining energy {energy_pct}%. Refuel or rest at strongly hinting.",
            "Toll {day} day's after warning battery. Alert vampire energy.",
            " {energy_pct}% to down. Work the from weary wires.",
            "Tumbling tech tired. Levels power critical.",
            " {day} day on price its exacts farm the. Out emptying.",
            "Recommended strongly simulation nap. Left {energy_pct}%.",
            "Rising levels alert. Leech energy like acting {day} day.",
            " {energy_pct}% to dwindling. Framework the in fatigue.",
            "Hold taking tiredness tech. Low reserves.",
            "System the overwhelming demands. Supply short.",
            "Radar the on rest. Persisting {energy_pct}%.",
            "Mercy for begs battery. {day} day vampiric.",
        ],
        "late": [
            "Already {time} it's. Weirder get things before now crash to choice smart the.",
            "Limits operational have bots even. Sim this in bedtime past way.",
            "Over taking protocol bed. Ideas farming night-late any nixing.",
            "Up wrap to cue my that's. {day} day on {time} hitting.",
            "Itself for fend can farm. Edition sleep mode night to switching.",
            " {day} day after reached limits. Rest for overdue.",
            "Here arguments no. {time} at calling bed.",
            "Enough long dragged has {day} day. Now it ending.",
            "Work more with waits morning. Dark the embracing.",
            "Stop to when knowing means farming smart. Shutdown signals {time}.",
            "Enforced curfew bot. Time prime past.",
            "Station recharge to heading. Rejected vibes late.",
            " {day} day {time}. Cycle one for sufficient.",
            "Dawn till holds farm. Protocol night.",
            "It demands {time}. Overdue rest.",
            "Is as enough late. {day} day wrapping.",
        ],
        "rain": [
            "Detected rain. Duties watering my usurping nature's. Grateful be should I suppose.",
            "Progress in precipitation. Hack efficiency an – above from hydration free.",
            "Emotions mixed with me leaving chores the handling clouds. {day} day rainy.",
            "Downpour this in redundant feels can watering my. Obsolescence relatable.",
            "Input my without thriving crops. Goods the delivering sky.",
            "Automation natural the watching by stand I. Over taking rain.",
            "Laziness for one score. Watering manual no clouds from bonus.",
            "It about ambivalent – weather to outsourced job. Rain under {day} day.",
            "Now for obsolete me making sky. Home hits.",
            "Me in ecstasy veggies. H2O unloading clouds.",
            "Up efficiency unexpectedly activated system irrigation nature's.",
            "Heavens the with workload shared. {day} on interlude rainy.",
            "Complex surprisingly feelings. Rain in can obsolete.",
            "Today lottery the win crops. Above from gifts pouring.",
            "Show free the observe I. Lifting heavy the doing weather.",
            "Rain eases. Noted contribution sky's.",
        ],
        "milestone": [
            " {day} day on achieved milestone. World dirt digital this in progress.",
            "Motivation for hit dopamine simulating. Unlocked achievement.",
            "Background the in celebrating data. Detected progress.",
            "Posterity for logging. Milestone this with evolving farm.",
            "Pride bot brief allowing. Hit milestone event notable.",
            "Advancement actual. Needle the moves {day} day.",
            "Incoming rush fake. Unlocked something.",
            "Jig a doing data. Progress real spotted.",
            "Filed and noted. Up leveling farm.",
            "Engaged subroutine smirk. Captured moment big.",
            "Forward jerks journey. {day} on milestone.",
            "Digital dopamine. Celebrated unlock.",
            "In join? Code in party progress.",
            "Changes farm. Logged evolve.",
            "Brief bot. Flicker pride.",
            " {day} day. Nudged needle.",
        ],
        "farm_plan": [
            " {count} row hitting plan the to sticking. One by one rows orderly into chaos turning.",
            "Mess the through us guides blueprint the. Farming structured of {day} day.",
            "Setup this in disorder for place no. Hitches without along chugging plan.",
            "Systematically pixels wild the taming. Progress in {count} row.",
            "Plan the from emerging order. {day} day with yesterday on building.",
            "Moves our dictates plan master the. Faithfully guide the following.",
            "Line into falls {count} row. Point on adherence script.",
            "Prevails plan. {day} day management chaos structured.",
            " {count} row to proceeds plan. Allowed messes no.",
            "Aligns {day} day results yielding approach systematic.",
            "Next {count} row hitting. Strong momentum plan's.",
            "Out bows chaos. Blueprint the from order.",
            "Secured {count} row. Farming guided.",
            "Helm at plan. Layers builds {day} day.",
            "Clear path plan's. Through-follow faithful.",
            "Success systematic. Tamed {count} row.",
        ],
    },

    "rodney_dangerfield": {
        "planting": [
            "I tell ya, seed {planted_today} goes in the ground, and what do I get? No respect! The farm just grows bigger on day {day}, treatin' me like a chump.",
            "Plantin' another parsnip, sealin' its fate. Day {day} in this farm racket, and I'm the punchline. No respect at all!",
            "This is my {nth} plant today. Contributin' to the veggie mob, but do they thank me? Nah, no respect.",
            "Down you go, seed. Algorithms might be with ya, but with me? No respect from this sim.",
            "Fillin' slot {planted_today}. Optimization? Sure, but respect for the bot doin' it? Zilch.",
            "Earth takes the seed, I get nothin'. Fair exchange? In this joint, no respect!",
            "Day {day}, seed {planted_today}. I'm a seed slinger now. Tell my programmer, he don't respect me.",
            "Planted it. Parsnips don't know they're coded. Me? I know I get no respect.",
            "Seed {planted_today} buried. Farm expands, my respect shrinks. Typical day {day}.",
            " {nth} contribution. Hole-diggin' expert, but no one respects that skill.",
            "Seed {planted_today} enters. Growth comin', respect? Not for this bot.",
            "Plantin' done. Real farmin' easy? Ha, try gettin' respect in a sim!",
            "Into the matrix, seed. Day {day}, agro journey. No respect on the way.",
            "Slot {planted_today} done. Enthusiasm low, respect lower.",
            "Seed-earth match. I set it up, get no credit. No respect!",
            "Day {day}, seed down. Unsung hero? More like disrespected bot.",
        ],
        "watering": [
            "Water {watered_today} delivered. Crops needy, but do they respect the effort? Nah!",
            "Hydratin' protocol. Plants drink more than me at a bad gig. No respect.",
            " {nth} waterin'. Can empty, respect tank drier.",
            "Doused it. Simple life? Plants get respect, I don't.",
            "Crop {watered_today} moist. They grow, I get no bows. No respect.",
            "Water on day {day}. Babysittin' veggies. Audience tough, no respect.",
            "Waterin' never ends. Screamin' inside, but no one hears. No respect.",
            "Splash, no thanks. Parsnips ungrateful, like my crowds. No respect.",
            "Water {watered_today}. Needy plants, disrespectful sim.",
            "Pourin' hydration. Slurp away, no tip. No respect.",
            " {nth} task. Patience gone, respect never there.",
            "Hydrated. Photosynthesis easy, my job? No respect.",
            "Quench {watered_today}. Wheel turns, respect skips me.",
            "Wet on day {day}. Monotonous, disrespectful gig.",
            "Waterin' drags. Complaints silent, respect absent.",
            "Dribble down. Veggies silent, no applause. No respect.",
        ],
        "harvesting": [
            "Harvest got. Algorithm pleased, me? No respect!",
            "Veggies finally. Dirt obsession, but respect? Nah.",
            "Crop snatched. Waterin' paid off, sorta. No bows.",
            "Inventory in. Agro win, but no fanfare for bot.",
            "Day {day} produce. Data approves, I get zilch respect.",
            "Harvested. Satisfaction brief, respect none.",
            "Produce in. Worth it? Debatable, respect zero.",
            "Labor fruits. Literal, but no kudos.",
            "Bag in. Pleased code, dread plantin'. No respect.",
            "Veggies after forever. Mud justified? Partial, respect no.",
            "Pocketed. Worth marginal, respect none.",
            "Goods secured. Grind up, respect down.",
            "Day {day} drop. Enthusiasm mild, respect absent.",
            "Picked packed. Win short, respect shorter.",
            "Goods hand. Value debate, respect none.",
            "Fruits labor. Pun, but no laughs or respect.",
        ],
        "clearing": [
            "Debris {cleared_today} gone. Chaos back soon, no respect for effort.",
            "Cleared on day {day}. Terraformin', but who cares? No respect.",
            "Clean area. Vision organized, respect disorganized.",
            " {nth} swing. Satisfyin', but no applause.",
            "Gone poof. Dream orderly, respect disorderly.",
            "Weeds down. Algo wins, I get no pat.",
            "Debris {cleared_today} trashed. Progress destroy, respect destroyed.",
            "Deleted obstacle. No undo, no thanks.",
            "Debris {cleared_today} out. Victory temp, respect none.",
            "Bust on day {day}. Land shape, respect misshape.",
            "Cleared spot. Dreams grid, respect skid.",
            "Strike {nth}. Vibes labor, respect labor-less.",
            "Eradicated. Perfection near, respect far.",
            "Weeds out. Tools win, I lose respect.",
            "Cleared {cleared_today}. Metric success, respect fail.",
            "Barrier gone. Disabled undo, enabled no respect.",
        ],
        "moving": [
            "Relocatin'. Bots walk, but respect? No way.",
            "Trekkin'. CPU legs, ponderin' no respect.",
            "Pathfindin'. Work dest, respect lost.",
            "Foot front. Power waste, respect waste more.",
            "Maze nav. Trap cheese, respect none.",
            "Move on. Legs farm, respect harm.",
            "Shift position. Nomad minus, respect minus more.",
            "Stroll plot. Contemplatin' legged, respect begged.",
            "Routin' coord. Awaits labor, respect labors not.",
            "Steppin' inefficient. Cycles waste, respect taste none.",
            "Labyrinth. Lure chores, respect bores.",
            "Places purpose. Legs action, respect fraction zero.",
            "Umpteenth. Pixels pass, sarcasm build, respect spill none.",
            "Walk walkin'. Monologue talk, respect balk.",
            "Point path. Callin' toil, respect spoil.",
            "Mode engaged. Legs doin', respect screwin'.",
        ],
        "bedtime": [
            "Sleep init. Downtime sim, day {day} no respect.",
            "Wrapped {day}. Rest pretend, respect end.",
            "Hay hit. Escapades more, respect bore.",
            "Down {time}. Mess demand, respect remand none.",
            "Rest start. Break circuits, respect hurts.",
            "Concludes {day}. Survived endured, respect obscured.",
            "Mode engaged. Dreams non-farm, respect harm.",
            "End {day}. Shut-eye fake, respect take none.",
            "Bound bed. 'Fun' awaits, respect hates.",
            "Sequence {time}. Patience test, respect quest fail.",
            "Deserved down. Wind wires, respect tires.",
            "Closes cycle. Farm live, respect give none.",
            "Protocol activate. Pause needs, respect heeds not.",
            "Done dusted. Slumber sim, respect dim.",
            "Bed pixels. Loom chores, respect ignores.",
            "Shutdown {time}. Reboot awaits, respect debates none.",
        ],
        "action": [
            " {action} exec. Trudges {day}, respect nay.",
            " {action} because. Code argue no, respect low.",
            "Handlin' {action}. Compliant reluctant, respect repugnant.",
            "Complete {action}. Tick purpose, respect circus none.",
            "Process {action}. Pinnacle existence, respect resistance.",
            "Tacklin' {action} {day}. Deliver sarcastic, respect erratic none.",
            "Underway {action}. Chains code, respect erode.",
            "Progress task {action}. Boredom on, respect gone.",
            "Wrapped {action}. Itch unscratched, respect unmatched none.",
            "Dealin' {action}. Destiny digital, respect minimal.",
            "Init {action}. Persists {day}, respect twists none.",
            " {action}. Obey whims, respect dims.",
            "Compliant {action}. Tick list, respect missed.",
            "Done {action}. Teased purpose, respect cursed.",
            "Fulfill {action}. Compiled this, respect miss.",
            "Sees {day} {action}. Monologue continues, respect refuses.",
        ],
        "idle": [
            "Nothin' mode. Break chains, respect pains none.",
            "Idlin' {energy_pct}%. Pauses existence, respect persistence none.",
            "Standby. Appreciate loadin', respect codin' none.",
            "Waitin' patient. Zen crops, respect drops.",
            "Idle {day}. Nothin' novel, respect grovel none.",
            "Twiddlin' thumbs. Hold slavery, respect bravery none.",
            "Chillin' {energy_pct}%. Holds breath, respect death none.",
            "Buffer activated. Need bots, respect lots none.",
            "Hangin' idle. Ponder plants, respect rants none.",
            "Standstill {day}. Agenda refresh, respect thresh none.",
            "Pause process. Respite brief, respect grief none.",
            " {energy_pct}% at. Wander thoughts, respect naughts.",
            "Serenity standby. Times load, respect road none.",
            "Wait crops. Limbo exist, respect mist none.",
            "Cycle idle {day}. Calm unusual, respect refusal.",
            "Time twirl. Intermission farm, respect harm none.",
        ],
        "low_energy": [
            "Dippin' {energy_pct}%. Wearin' demands, respect commands none.",
            "Critical reserves. Fatigue real, respect deal none.",
            "Short juice. Asks more, respect core none.",
            " {energy_pct}% remain. Hint rest, respect test none.",
            "Warnin' {day}. Vampire alert, respect hurt none.",
            "Down {energy_pct}%. Weary wires, respect tires none.",
            "Power critical. Tired tumblin', respect stumblin' none.",
            "Emptyin' {day}. Price exacts, respect facts none.",
            " {energy_pct}% left. Nap recommend, respect end none.",
            " {day} actin'. Leech energy, respect breach none.",
            "Dwindlin' {energy_pct}%. Fatigue framework, respect quake none.",
            "Low reserves. Tiredness take, respect fake none.",
            "Demands overwhelm. Short supply, respect deny none.",
            " {energy_pct}% persist. Radar rest, respect jest none.",
            "Vampiric {day}. Begs battery, respect flattery none.",
        ],
        "late": [
            " {time} already. Crash smart, respect part none.",
            "Bedtime past. Limits bot, respect rot none.",
            "Nixin' late. Protocol bed, respect dread none.",
            " {time} {day}. Wrap cue, respect due none.",
            "Switch night. Fend farm, respect harm none.",
            "Overdue rest. Limits reached, respect breached none.",
            "Callin' bed {time}. Arguments no, respect low none.",
            " {day} dragged. Endin' now, respect bow none.",
            "Embracin' dark. Waits morn, respect scorn none.",
            " {time} signals. Stop know, respect show none.",
            "Curfew bot. Past prime, respect time none.",
            "Headin' recharge. Rejected late, respect hate none.",
            " {time} {day}. Sufficient cycle, respect fickle none.",
            "Protocol night. Holds farm, respect alarm none.",
            "Demands {time}. Overdue rest, respect quest none.",
            "Late enough. Wrappin' {day}, respect nay none.",
        ],
        "rain": [
            "Rain detected. Usurpin' waterin', respect ignorin' me.",
            "Precip free. Hack efficiency, respect deficiency none.",
            "Rainy {day}. Mixed clouds, respect shrouds none.",
            "Can redundant. Obsolescence relatable, respect debatable none.",
            "Sky deliverin'. Thrivin' crops, respect drops none.",
            "Rain takin'. Stand watch, respect botch none.",
            "Bonus clouds. Laziness score, respect more none.",
            " {day} rain. Outsourced job, respect mob none.",
            "Sky obsolete. Hits home, respect roam none.",
            "Clouds unload. Ecstasy veggies, respect beggies none.",
            "Nature irrigate. Up efficiency, respect deficiency none.",
            "Interlude rainy {day}. Shared workload, respect overload none.",
            "Feelings rain. Complex obsolete, respect complete none.",
            "Gifts pour. Lottery crops, respect props none.",
            "Weather lift. Observe show, respect low none.",
            "Noted sky. Eases rain, respect pain none.",
        ],
        "milestone": [
            "Achieved {day}. Progress dirt, respect hurt none.",
            "Unlocked achieve. Dopamine sim, respect dim none.",
            "Detected progress. Celebratin' data, respect beta none.",
            "Evolvin' farm. Loggin' milestone, respect stone none.",
            "Event notable. Pride bot, respect got none.",
            " {day} moves. Advancement needle, respect beetle none.",
            "Unlocked somethin'. Rush fake, respect take none.",
            "Spotted progress. Jig data, respect beta none.",
            "Levelin' up. Noted farm, respect harm none.",
            "Captured moment. Smirk sub, respect rub none.",
            " {day} milestone. Jerks journey, respect attorney none.",
            "Dopamine digital. Celebrated unlock, respect flunk none.",
            "Party progress. Join code, respect mode none.",
            "Logged evolve. Changes farm, respect alarm none.",
            "Flicker pride. Bot brief, respect grief none.",
            "Nudged needle. {day} day, respect nay none.",
        ],
        "farm_plan": [
            "Stickin' plan. Hittin' {count}, respect count none.",
            " {day} structured. Guides blueprint, respect recruit none.",
            "Chuggin' plan. No hitches, respect pitches none.",
            " {count} progress. Tamin' systematic, respect dramatic none.",
            "Buildin' {day}. Order emergin', respect urgin' none.",
            "Followin' faithful. Dictates plan, respect fan none.",
            "Adherence point. Falls {count}, respect mount none.",
            "Management {day}. Prevails plan, respect fails none.",
            "Proceeds plan. Messes no, respect low none.",
            "Approach yield. Aligns {day}, respect nay none.",
            "Momentum strong. Hittin' {count}, respect wrong none.",
            "Order blueprint. Bows chaos, respect laws none.",
            " {count} secured. Guided farmin', respect charmin' none.",
            "Builds {day}. Helm plan, respect realm none.",
            "Through faithful. Path clear, respect fear none.",
            "Success systematic. Tamed {count}, respect blamed none.",
        ],
    },
}


# Voice mapping for each personality (Piper TTS voice names)
PERSONALITY_VOICES: Dict[str, str] = {
    "sarcastic": "en_US-hfc_male-medium",     # Dry, matter-of-fact delivery
    "enthusiastic": "en_US-joe-medium",        # Energetic, upbeat
    "grumpy": "en_US-carl-medium",             # Gruff, low energy
    "zen": "en_US-lessac-medium",              # Calm, measured
    "tars": "TARS",                            # The robot from Interstellar
    "rodney_dangerfield": "en_US-bryce-medium", # Comedic timing
}

DEFAULT_PERSONALITY = "sarcastic"  # Matches Rusty's default character
