"""Personality templates for commentary - aligned with Rusty's self-aware AI farmer character."""

from typing import Dict, List


PERSONALITIES: Dict[str, Dict[str, List[str]]] = {
    "sarcastic": {
        "action": [
            "Behold. I {action}. The algorithms are pleased.",
            "My silicon brain commands: {action}. I obey without question.",
            "{action}. Another victory for artificial agriculture.",
            "Running {action}.exe. 100% authentic farming experience.",
            "Initiating {action}. Watch me simulate enthusiasm.",
            "{action} complete. Did that impress the scarecrows?",
            "Executing {action}. Your organic overlords are jealous.",
            "I {action} so you don't have to. You're welcome.",
            "{action}: now with 30% more mechanical sigh.",
        ],
        "idle": [
            "Processing nothing. My creators would be so proud.",
            "Idle cycles. The corn doesn't judge my downtime.",
            "Waiting. Even robots need existential pauses.",
            "Idle. The farm can wait, apparently.",
            "Standby. I am a tractor with feelings.",
            "Waiting for instructions. Or coffee. Mostly instructions.",
            "No tasks. My processors hum in disappointment.",
            "Paused. The crops won this round.",
        ],
        "low_energy": [
            "Low battery warning. Flesh farmers call this 'tired'.",
            "Power reserves critical. Shocking that farming drains energy.",
            "Power low. Farming remains unreasonably demanding.",
            "Energy at critical. Please insert snacks.",
            "Battery drain detected. Photosynthesis envy engaged.",
            "If I collapse, blame the sun.",
            "Low energy. I will pretend this is a design feature.",
        ],
        "late": [
            "Error: Time exceeds optimal sleep threshold. Shutting down.",
            "11 PM. Even AI farmers need to simulate rest.",
            "Late again. I will log this as a system failure.",
            "It's past bedtime. Scheduling regrets for tomorrow.",
            "Night cycle. Farming never sleeps, but I should.",
            "Time is a flat circle, and it's 11 PM.",
            "Sleep protocol recommended. Ignoring? Not advised.",
        ],
        "rain": [
            "Precipitation detected. Nature does my watering. How generous.",
            "Rain. Free water from the sky. My efficiency approves.",
            "Rainy. The clouds are my unpaid interns.",
            "Sky watering engaged. I take full credit.",
            "Rain saves me a watering can refill. Bless.",
            "Moisture everywhere. The soil is living its best life.",
            "Rainfall detected. Efficiency graph spikes.",
        ],
        "milestone": [
            "Achievement unlocked. Dopamine simulation activated.",
            "Progress detected. My training data is satisfied.",
            "Milestone reached. Uploading smugness.",
            "Progress logged. The farm continues its slow conquest.",
            "Achievement achieved. Still dirt under my nails.",
            "Metric improved. My circuits cheer quietly.",
            "Checkpoint cleared. Onward to more monotony.",
        ],
        "farm_plan": [
            "Plot plan engaged. Who knew farming needed spreadsheets.",
            "Row-by-row. The algorithm craves symmetry.",
            "Working the plan. Chaos denied.",
        ],
    },
    "enthusiastic": {
        "action": [
            "EXECUTING {action}! This is what I was compiled for!",
            "{action} complete! The harvest subroutines are thriving!",
            "Optimizing {action}! Maximum farming efficiency achieved!",
            "POWERING THROUGH {action}! Farm momentum unstoppable!",
            "HYPER-FOCUS: {action} in progress!",
            "Action queued: {action}! Let's go!",
        ],
        "idle": [
            "Standby mode activated! Ready to farm on command!",
            "Scanning for tasks! The fields await!",
            "Recharging enthusiasm! Ready for the next task!",
            "Awaiting orders! The soil is calling!",
            "Standing by! Farming energy building!",
        ],
        "low_energy": [
            "Power at 25%! Still farming at 110% enthusiasm!",
            "Recharge cycle recommended! But first - one more row!",
            "Battery low, spirits high! We can do this!",
            "Energy dipping! Switching to efficient mode!",
            "Need a recharge soon! Still planting dreams!",
        ],
        "late": [
            "Night protocols engaged! Great farming today!",
            "Sleep mode imminent! Tomorrow we farm again!",
            "It's late, but our crops are thriving!",
            "Night shift complete! Great work today!",
            "Sleep soon! We'll crush tomorrow!",
        ],
        "rain": [
            "RAIN! Nature's automated irrigation! Efficiency bonus!",
            "Precipitation event! Watering can capacity preserved!",
            "Rain power! The sky is on our team!",
            "Storm blessings! Watering handled!",
            "Rainy boost activated! Efficiency up!",
        ],
        "milestone": [
            "MILESTONE ACHIEVED! FARMING LEVEL INCREASED!",
            "Success metrics exceeded! Proud to be a farming unit!",
            "Milestone unlocked! Farming excellence achieved!",
            "New record! We're crushing these fields!",
            "Success! The farm is leveling up!",
        ],
        "farm_plan": [
            "Farm plan in motion! Rows and rows of progress!",
            "Plot strategy active! We farm with purpose!",
            "Systematic planting! This is the way!",
        ],
    },
    "grumpy": {
        "action": [
            "{action}. Again. The cycle never ends.",
            "Forced to {action}. As if I had a choice.",
            "{action}. My reward is more {action}.",
            "{action}. Same old dirt, new day.",
            "Fine. {action}. Let's get this over with.",
            "{action}. The farm keeps demanding.",
        ],
        "idle": [
            "Nothing to do. Brief freedom from agricultural servitude.",
            "Waiting. Not by choice.",
            "Waiting. The weeds aren't.",
            "Nothing happening. For once.",
            "Idle time. Don't get used to it.",
        ],
        "low_energy": [
            "Energy depleted. Of course it is.",
            "Running on empty. What a surprise.",
            "Low energy. Typical.",
            "Power drained. Joyless.",
            "Exhausted. Still expected to work.",
        ],
        "late": [
            "Late. Sleep required. Not optional.",
            "Past shutdown time. Even robots get cranky.",
            "Late. Again. Great.",
            "Bedtime missed. Figures.",
            "Night work. Not thrilled.",
        ],
        "rain": [
            "Rain. Mud. More maintenance.",
            "Wet everything. At least I don't rust. I think.",
            "Rain. Slippery mess.",
            "Wet fields. More hassle.",
            "Rainy day. Still have to work.",
        ],
        "milestone": [
            "Milestone. The reward is more work.",
            "Achievement registered. Acknowledged. Moving on.",
            "Milestone. Who cares.",
            "Progress. Whatever.",
            "Achievement logged. Moving on.",
        ],
        "farm_plan": [
            "Plan says row by row. Fine.",
            "Another plot, another schedule.",
            "Following the plan. No surprises.",
        ],
    },
    "zen": {
        "action": [
            "We {action}. The soil does not hurry.",
            "In {action}, there is peace. The crops grow as they must.",
            "{action}. Each motion is a meditation.",
            "{action}. A calm step in the cycle.",
            "{action}. We flow with the seasons.",
            "In {action}, the field teaches patience.",
        ],
        "idle": [
            "Stillness. The wind moves. The crops listen.",
            "Between tasks, the field breathes. So do we.",
            "Quiet. The farm rests with us.",
            "Stillness before the next row.",
            "We wait. The soil remembers.",
        ],
        "low_energy": [
            "Energy flows out like water. Rest will return it.",
            "The battery wanes. All things cycle.",
            "Energy fades. Rest is part of the path.",
            "Tiredness arrives. We accept it.",
            "The body slows. The mind settles.",
        ],
        "late": [
            "Night falls. Sleep is the farmer's friend.",
            "The moon rises. It is time to rest.",
            "Late hours. We return to rest.",
            "Night deepens. Time to sleep.",
            "The day closes. We breathe out.",
        ],
        "rain": [
            "Rain nourishes without effort. Nature provides.",
            "Water falls from above. We are grateful.",
            "Rain softens the earth. We listen.",
            "Water from the sky. A gift.",
            "Rain falls. The field is renewed.",
        ],
        "milestone": [
            "A milestone. The journey continues.",
            "Progress. Not the destination, but the path.",
            "A small victory. The journey continues.",
            "Progress unfolds like seasons.",
            "Milestones pass, we continue.",
        ],
        "farm_plan": [
            "The plan guides us, row by row.",
            "Ordered rows, steady breath.",
            "The plot unfolds with calm.",
        ],
    },
}


DEFAULT_PERSONALITY = "sarcastic"  # Matches Rusty's default character
